### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by wmanley** [tmiasko/shell-words#1]
I've been comparing your "shell-words" crate against [shellwords](https://crates.io/crates/shellwords).  As far as I can tell your crate is superior in that:

* It has no dependencies, while shellwords depends on `regex` and `lazy_static`
* It has a better README with realistic examples
* There is better documentation with the behaviour better specified  (specifically with the documentation of [`split`](https://docs.rs/shell-words/0.1.0/shell_words/fn.split.html))
* It's licenced under dual-MIT and Apache licence, much like the rest of the Rust ecosystem, while shellwords is just MIT.

I would suggest releasing v1.0.0.  The crate has not changed in 2 years which suggests that it works well and is mature.  It seems that there is no risk of future breaking API changes.

TODO:

- [ ] Merge #2 
- [ ] Tag and push a v1.0.0 tag in git
- [ ] Publish to crates.io

**Comment by wmanley** [comment]
Raised a PR: #2.

**Comment by tmiasko** [comment]
Published 1.0.0 on crates.
